server:
  port: 9527
spring:
  application:
    name: microservice-zuul-gateway9527
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gatway9527.com
    prefer-ip-address: true
zuul:
#  prefix: /xue
#  ignored-services: "*"
  routes:
    mydept.serviceId: MICROSERVICE-PROVIDER-DEPT
#    mydept.path: /mydept/**
info:
  app.name: xue-microservice
  company.name: www.xue.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$