server:
  port: 80
  
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
spring:
  application:
    name: microservice-consumer-dept-80
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false
  instance:
    instance-id: microservice-consumer-dept80
    prefer-ip-address: true
info:
  app.name: xue-microservice
  company.name: www.xue.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$